### ISSUE TITLE
Validator only allows & with &amp;

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/TokenScript#238]
In queries to a server the validator will throw if & is given without &amp, a little too strict I think

**Comment by colourful-land** [comment]
Can you try to use ';' instead of '&' in the URI? IETF at certain point admitted that it's a poor choice to design HTTP to use & to separate arguments because it's just terrible coordination with w3c.

Read this:

https://stackoverflow.com/questions/3481664/semicolon-as-url-query-separator

In fact, web servers already accept `;` as separator since when I was in college. I feel Spring supports it by default. Have you tried?

We can't change that from XML end.
