### ISSUE TITLE
Set-up tokenscript.org

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/TokenScript#25]
It can be contributed by everyone as well.
Like "http://erc721.org/" is fine 
https://github.com/0xProject/erc721-website

this domain is still available, TokenBehaviourMarkupLanguage.org

**Comment by colourful-land** [comment]
What you ask for is a project. Let's make tasks out of the project so it is actionable.

I'll set up a single-page website at tokenscript.org then close this issue, so if you want specifics you can ask new ones, like creating an issue 'add a code snippet example on the website".

Meta-issues and metaphysics issues can't be actioned, e.g. "we need a website to attract partners", since it's not a task. Such issues will be closed.

**Comment by colourful-land** [comment]
Done.
