### ISSUE TITLE
lack of clarity of the visual rendering of the example AdmissionTicket.xml

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/TokenScript#73]
1. The wallet tab’s tokenIconfied rows remains natively rendered (for now).

2. the previous sample XSL/TokenScript files that was created [1] should go into token.en:

```
      <ts:token-card>
      <ts:view-iconified xml:lang="en">
        <p>An Admission Ticket Token</p>
      </ts:view-iconified>
      <ts:view xml:lang="en">
        &token.en;
      </ts:view>
    </ts:token-card>
```

  and be read from there, used to render tokenInstanceIconified rows, which is displayed when we tap on a tokenIconfied row in the Wallet tab.

3. When the user taps on that tokenInstanceIconified row, render XXX with the button "Enter" and back.

4. When the user taps the "Enter" button render enter.en.

What do we display at step 2 (XXX)? Do we display this screen, using tokenInstanceIconified (with the Next replaced by Enter and the price/quantity bits removed)

[1] https://github.com/AlphaWallet/contracts/tree/reactive-in-app/tbml-mobile-app/tokenscript

![Simulator Screen Shot - iPhone X - 2019-04-03 at 13 20 13](https://user-images.githubusercontent.com/56189/55455688-28c8de00-5617-11e9-8e30-c2c1db2a927e.png)

Good to know: @James-Sangalli  @JamesSmartCell

**Comment by colourful-land** [comment]
> When the user taps on that tokenInstanceIconified row, render XXX with the button "Enter" and back.

We haven't designed inheritance and this is perhaps better not hurried. Which means the typical ERC721 or ERC875 functions like `transfer()` doesn't have a corresponding action described by Tokenscript. Therefore, the current thinking is to render transfer function (and send, for magic link generation if it is ERC875) in a hardcoded fashion.

What we can do is to amend this:

      <ts:contract id="ecr875" type="holding">
       <ts:address network="3">0x16e58F9a98bc46a572CFb9ce28DDEeaf76AF645a</ts:address>
      </ts:contract>

With this:


      <ts:contract id="ecr875" type="holding">
       <ts:address network="3" interface="erc875">0x16e58F9a98bc46a572CFb9ce28DDEeaf76AF645a</ts:address>
      </ts:contract>

So that the wallet knows to render the ERC875 functions. It's probably not forward compatible with TokenScript inheritance if we decide to go that route.

**Comment by colourful-land** [comment]
This issue is solved by updating the wiki

https://github.com/AlphaWallet/TokenScript/wiki/Nomenclature---Iconified-Views
